services:
  web:
    build: .
    volumes:
      - .:/var/www/app
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pfadiheim.rule=Host(`www.pfadiheim-buelach.ch`)"
      - "traefik.http.routers.pfadiheim.entrypoints=websecure"
      - "traefik.http.routers.pfadiheim.tls.certresolver=letsencrypt"
      - "traefik.http.services.pfadiheim.loadbalancer.server.port=80"

networks:
  traefik:
    external: true
